"""Test viz data service — all viz type generators with exact value assertions.

Viz data is ALWAYS deterministic from metrics. Never generated by Claude.
"""
from datetime import date

import pytest

from app.database import SessionLocal
from app.models.property import Property
from app.models.config import ClientConfig
from app.services.metrics_engine import compute_property_metrics
from app.services import viz_data_service as viz

REF_DATE = date(2026, 3, 15)


@pytest.fixture(scope="module")
def db():
    session = SessionLocal()
    yield session
    session.close()


@pytest.fixture(scope="module")
def metrics_b(db):
    prop = db.query(Property).filter_by(code="PROP-B").first()
    config = db.query(ClientConfig).filter_by(property_id=prop.id, is_active=True).first()
    cd = {k: getattr(config, k) or {} for k in [
        "occupancy_thresholds", "exposure_thresholds", "pricing_tolerance",
        "concession_policy", "renewal_policy", "lease_term_policy",
        "experiment_policy", "amenity_benchmarks",
    ]}
    return compute_property_metrics(db, str(prop.id), cd, REF_DATE)


@pytest.fixture(scope="module")
def combined_metrics(db):
    """Metrics for both properties combined."""
    all_ut = {}
    portfolio_total = {"total_units": 0, "total_vacant": 0, "total_monthly_vacancy_cost": 0}
    for code in ("PROP-A", "PROP-B"):
        prop = db.query(Property).filter_by(code=code).first()
        config = db.query(ClientConfig).filter_by(property_id=prop.id, is_active=True).first()
        cd = {k: getattr(config, k) or {} for k in [
            "occupancy_thresholds", "exposure_thresholds", "pricing_tolerance",
            "concession_policy", "renewal_policy", "lease_term_policy",
            "experiment_policy", "amenity_benchmarks",
        ]}
        m = compute_property_metrics(db, str(prop.id), cd, REF_DATE)
        all_ut.update(m["unit_type_metrics"])
        pm = m["portfolio_metrics"]
        portfolio_total["total_units"] += pm["total_units"]
        portfolio_total["total_vacant"] += pm["total_vacant"]
        portfolio_total["total_monthly_vacancy_cost"] += pm["total_monthly_vacancy_cost"]

    # Compute blended occupancy
    total_occ = sum(m["occupancy_metrics"]["occupied"] for m in all_ut.values())
    portfolio_total["blended_occupancy"] = total_occ / portfolio_total["total_units"]
    portfolio_total["worst_performing_unit_type"] = "B1"
    portfolio_total["best_performing_unit_type"] = "A1"

    return {"unit_type_metrics": all_ut, "portfolio_metrics": portfolio_total}


class TestScoreGauge:
    def test_score_gauge_structure(self):
        gauge = viz.generate_score_gauge({"portfolio_assessment": {"overall_portfolio_score": 42}})
        assert gauge["score"] == 42
        assert gauge["max"] == 100
        assert len(gauge["zones"]) == 5

    def test_score_gauge_zone_labels(self):
        gauge = viz.generate_score_gauge({})
        labels = [z["label"] for z in gauge["zones"]]
        assert labels == ["Crisis", "Distressed", "Imbalanced", "Opportunity", "Optimized"]

    def test_score_gauge_uses_revenue_efficiency(self):
        """When metrics has revenue_efficiency, prefer that over diagnosis score."""
        diag = {"portfolio_assessment": {"overall_portfolio_score": 42}}
        metrics = {"revenue_efficiency": {"revenue_efficiency_score": 73}}
        gauge = viz.generate_score_gauge(diag, metrics)
        assert gauge["score"] == 73

    def test_score_gauge_falls_back_to_diagnosis(self):
        """When metrics has no revenue_efficiency, use diagnosis score."""
        diag = {"portfolio_assessment": {"overall_portfolio_score": 42}}
        gauge = viz.generate_score_gauge(diag, {})
        assert gauge["score"] == 42


class TestKPICards:
    def test_card_count(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        assert len(cards) == 6

    def test_total_units(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        assert cards[0]["value"] == "156"

    def test_total_vacant(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        assert cards[2]["value"] == "18"  # 2+5+5+6

    def test_card_labels(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        labels = [c["label"] for c in cards]
        assert "Revenue Gap $/mo" in labels
        assert "Renewal Opportunity $/yr" in labels
        assert "Revenue Efficiency %" in labels
        # Removed: Monthly Vacancy Cost
        assert "Monthly Vacancy Cost" not in labels

    def test_cards_with_missing_sections(self):
        """KPI cards should not crash when revenue_gap/renewal_opportunity missing."""
        minimal = {"portfolio_metrics": {"total_units": 10, "total_vacant": 2, "blended_occupancy": 0.8}}
        cards = viz.generate_kpi_cards(minimal)
        assert len(cards) == 6
        # Revenue Gap should show $0
        gap_card = [c for c in cards if c["label"] == "Revenue Gap $/mo"][0]
        assert gap_card["value"] == "$0"


class TestDataTable:
    def test_row_count(self, combined_metrics):
        table = viz.generate_data_table(combined_metrics)
        assert len(table["rows"]) == 4

    def test_b1_values(self, combined_metrics):
        table = viz.generate_data_table(combined_metrics)
        b1 = [r for r in table["rows"] if r["unit_type"] == "B1"][0]
        assert b1["occupied"] == 19
        assert b1["vacant"] == 5
        assert b1["occ_rate"] == 0.79
        assert b1["asking"] == 1525
        assert b1["comps"] == 1434

    def test_highlights_include_b1(self, combined_metrics):
        table = viz.generate_data_table(combined_metrics)
        assert len(table["highlights"]) > 0
        occ_highlights = [h for h in table["highlights"] if h["col"] == "occ_rate"]
        assert any(h["color"] == "#DC2626" for h in occ_highlights)  # B1 crisis color

    def test_new_columns_present(self, combined_metrics):
        """Data table now includes optimal_asking, revenue_gap, elasticity_confidence."""
        table = viz.generate_data_table(combined_metrics)
        col_keys = [c["key"] for c in table["columns"]]
        assert "optimal_asking" in col_keys
        assert "revenue_gap" in col_keys
        assert "elasticity_confidence" in col_keys

    def test_gap_magnitude_highlights(self):
        """Revenue gap column should be highlighted by gap magnitude."""
        # Create metrics with a large gap for one unit type
        metrics_with_gap = {
            "unit_type_metrics": {
                "B1": {"revenue_gap": {"total_gap_monthly": 8000}, "optimal_pricing": {}, "elasticity": {}},
            }
        }
        table = viz.generate_data_table(metrics_with_gap)
        gap_highlights = [h for h in table["highlights"] if h["col"] == "revenue_gap"]
        assert any(h["color"] == "#DC2626" for h in gap_highlights)


class TestRentWaterfall:
    def test_b1_waterfall(self):
        wf = viz.generate_rent_waterfall("B1")
        assert len(wf) == 6
        assert wf[0]["value"] == 1405  # Base
        assert wf[1]["value"] == 125   # Amenity
        assert wf[2]["value"] == 1530  # Predicted

    def test_a1_waterfall(self):
        wf = viz.generate_rent_waterfall("A1")
        assert wf[0]["value"] == 1240
        assert wf[2]["value"] == 1329  # predicted = 1240 + 89

    def test_waterfall_with_optimal(self):
        """When metrics contain optimal_asking, an Optimal bar should appear."""
        metrics = {
            "unit_type_metrics": {
                "B1": {"optimal_pricing": {"optimal_asking": 1480}},
            }
        }
        wf = viz.generate_rent_waterfall("B1", metrics)
        labels = [b["label"] for b in wf]
        assert "Optimal" in labels
        optimal_bar = [b for b in wf if b["label"] == "Optimal"][0]
        assert optimal_bar["value"] == 1480
        assert optimal_bar["color"] == "#7C3AED"
        # Should have 7 bars (base + amenity + predicted + optimal + asking + comps + in-place)
        assert len(wf) == 7

    def test_waterfall_without_optimal(self):
        """When metrics lack optimal_asking, no Optimal bar."""
        wf = viz.generate_rent_waterfall("B1")
        labels = [b["label"] for b in wf]
        assert "Optimal" not in labels
        assert len(wf) == 6


class TestLineCharts:
    def test_four_unit_types(self):
        charts = viz.generate_line_charts()
        assert len(charts) == 4
        codes = {c["unit_type"] for c in charts}
        assert codes == {"A1", "A2", "B1", "B2"}

    def test_b1_occupancy_trend(self):
        charts = viz.generate_line_charts()
        b1 = [c for c in charts if c["unit_type"] == "B1"][0]
        occ_values = [s["occupancy"] for s in b1["series"]]
        assert occ_values == [0.88, 0.83, 0.79, 0.79]

    def test_b1_comps_trend(self):
        charts = viz.generate_line_charts()
        b1 = [c for c in charts if c["unit_type"] == "B1"][0]
        comp_values = [s["comps"] for s in b1["series"]]
        assert comp_values == [1475, 1460, 1445, 1434]

    def test_line_charts_with_optimal(self):
        """When metrics contain optimal_asking, line charts include it."""
        metrics = {
            "unit_type_metrics": {
                "B1": {"optimal_pricing": {"optimal_asking": 1480}},
            }
        }
        charts = viz.generate_line_charts(metrics)
        b1 = [c for c in charts if c["unit_type"] == "B1"][0]
        assert b1["optimal_price"] == 1480


class TestRevenueGapWaterfall:
    def test_structure(self):
        metrics = {
            "revenue_gap": {
                "current_monthly_revenue": 100000,
                "optimal_monthly_revenue": 120000,
                "vacancy_cost": 10000,
                "new_lease_underpricing": 5000,
                "renewal_opportunity": 3000,
                "concession_drag": 1000,
            }
        }
        result = viz.generate_revenue_gap_waterfall(metrics)
        assert "segments" in result
        segments = result["segments"]
        assert len(segments) == 6

        # Verify structure
        assert segments[0]["label"] == "Current Revenue"
        assert segments[0]["type"] == "base"
        assert segments[0]["value"] == 100000

        assert segments[1]["label"] == "+ Fill Vacant"
        assert segments[1]["type"] == "addition"
        assert segments[1]["value"] == 10000

        assert segments[4]["label"] == "- Concession Drag"
        assert segments[4]["type"] == "subtraction"
        assert segments[4]["value"] == -1000  # Negated

        assert segments[5]["label"] == "= Optimal Revenue"
        assert segments[5]["type"] == "total"
        assert segments[5]["value"] == 120000

    def test_empty_metrics(self):
        """Should return zero-value segments when revenue_gap is missing."""
        result = viz.generate_revenue_gap_waterfall({})
        assert "segments" in result
        assert len(result["segments"]) == 6
        assert result["segments"][0]["value"] == 0


class TestRevenueRoadmap:
    def test_structure(self):
        metrics = {
            "revenue_gap": {
                "current_monthly_revenue": 100000,
                "optimal_monthly_revenue": 120000,
                "vacancy_cost": 10000,
                "new_lease_underpricing": 5000,
                "renewal_opportunity": 3000,
                "concession_drag": 1000,
            }
        }
        result = viz.generate_revenue_roadmap(metrics, {})
        assert result["current_monthly"] == 100000
        assert result["projected_monthly"] <= 120000
        assert len(result["levers"]) == 4
        lever_names = [lev["lever"] for lev in result["levers"]]
        assert lever_names == ["FILL", "REPRICE", "RENEW", "DE_CONCESSION"]

    def test_empty_metrics(self):
        result = viz.generate_revenue_roadmap({}, {})
        assert result["current_monthly"] == 0
        assert result["projected_monthly"] == 0
        assert len(result["levers"]) == 4


class TestDimensionBreakdown:
    def test_structure(self):
        metrics = {
            "revenue_efficiency": {
                "revenue_efficiency_score": 65,
                "occupancy_zone": "SLIGHT_OVERSUPPLY",
                "dimensions": {
                    "occupancy_health": {"score": 60, "weight": 0.40},
                    "pricing_alignment": {"score": 70, "weight": 0.35},
                    "rent_roll_momentum": {"score": 65, "weight": 0.25},
                },
            }
        }
        result = viz.generate_dimension_breakdown(metrics)
        assert len(result["dimensions"]) == 3
        assert result["occupancy_zone"] == "SLIGHT_OVERSUPPLY"
        assert result["composite_score"] == 65

    def test_weights_sum_to_one(self):
        metrics = {
            "revenue_efficiency": {
                "revenue_efficiency_score": 65,
                "occupancy_zone": "BALANCED",
                "dimensions": {
                    "occupancy_health": {"score": 60, "weight": 0.40},
                    "pricing_alignment": {"score": 70, "weight": 0.35},
                    "rent_roll_momentum": {"score": 65, "weight": 0.25},
                },
            }
        }
        result = viz.generate_dimension_breakdown(metrics)
        total_weight = sum(d["weight"] for d in result["dimensions"])
        assert abs(total_weight - 1.0) < 0.001

    def test_default_weights_sum_to_one(self):
        """Even with empty metrics, default weights should sum to 1.0."""
        result = viz.generate_dimension_breakdown({})
        total_weight = sum(d["weight"] for d in result["dimensions"])
        assert abs(total_weight - 1.0) < 0.001
        assert len(result["dimensions"]) == 3

    def test_dimension_colors(self):
        result = viz.generate_dimension_breakdown({})
        colors = [d["color"] for d in result["dimensions"]]
        assert colors == ["#3B82F6", "#8B5CF6", "#10B981"]


class TestStackedBarRemoved:
    def test_no_stacked_bar_function(self):
        """generate_stacked_bar should no longer exist."""
        assert not hasattr(viz, "generate_stacked_bar")


class TestDailyBurn:
    def test_daily_burn_values(self, combined_metrics):
        burn = viz.generate_daily_burn_counter(combined_metrics)
        # Total: 91 + 235 + 254 + 331 = 911
        assert burn["daily_amount"] == 911
        assert burn["monthly_amount"] == 911 * 30
        assert burn["annual_amount"] == 911 * 365


class TestBeforeAfter:
    def test_has_three_metrics(self, combined_metrics):
        ba = viz.generate_before_after(combined_metrics, {})
        assert len(ba) == 3
        metric_names = {item["metric"] for item in ba}
        assert "Blended Occupancy" in metric_names
        assert "Total Vacant" in metric_names
        assert "Monthly Vacancy Cost" in metric_names
