"""Test viz data service — all 14 viz type generators with exact value assertions.

Viz data is ALWAYS deterministic from metrics. Never generated by Claude.
"""
from datetime import date

import pytest

from app.database import SessionLocal
from app.models.property import Property
from app.models.config import ClientConfig
from app.services.metrics_engine import compute_property_metrics
from app.services import viz_data_service as viz

REF_DATE = date(2026, 3, 15)


@pytest.fixture(scope="module")
def db():
    session = SessionLocal()
    yield session
    session.close()


@pytest.fixture(scope="module")
def metrics_b(db):
    prop = db.query(Property).filter_by(code="PROP-B").first()
    config = db.query(ClientConfig).filter_by(property_id=prop.id, is_active=True).first()
    cd = {k: getattr(config, k) or {} for k in [
        "occupancy_thresholds", "exposure_thresholds", "pricing_tolerance",
        "concession_policy", "renewal_policy", "lease_term_policy",
        "experiment_policy", "amenity_benchmarks",
    ]}
    return compute_property_metrics(db, str(prop.id), cd, REF_DATE)


@pytest.fixture(scope="module")
def combined_metrics(db):
    """Metrics for both properties combined."""
    all_ut = {}
    portfolio_total = {"total_units": 0, "total_vacant": 0, "total_monthly_vacancy_cost": 0}
    for code in ("PROP-A", "PROP-B"):
        prop = db.query(Property).filter_by(code=code).first()
        config = db.query(ClientConfig).filter_by(property_id=prop.id, is_active=True).first()
        cd = {k: getattr(config, k) or {} for k in [
            "occupancy_thresholds", "exposure_thresholds", "pricing_tolerance",
            "concession_policy", "renewal_policy", "lease_term_policy",
            "experiment_policy", "amenity_benchmarks",
        ]}
        m = compute_property_metrics(db, str(prop.id), cd, REF_DATE)
        all_ut.update(m["unit_type_metrics"])
        pm = m["portfolio_metrics"]
        portfolio_total["total_units"] += pm["total_units"]
        portfolio_total["total_vacant"] += pm["total_vacant"]
        portfolio_total["total_monthly_vacancy_cost"] += pm["total_monthly_vacancy_cost"]

    # Compute blended occupancy
    total_occ = sum(m["occupancy_metrics"]["occupied"] for m in all_ut.values())
    portfolio_total["blended_occupancy"] = total_occ / portfolio_total["total_units"]
    portfolio_total["worst_performing_unit_type"] = "B1"
    portfolio_total["best_performing_unit_type"] = "A1"

    return {"unit_type_metrics": all_ut, "portfolio_metrics": portfolio_total}


class TestScoreGauge:
    def test_score_gauge_structure(self):
        gauge = viz.generate_score_gauge({"portfolio_assessment": {"overall_portfolio_score": 42}})
        assert gauge["score"] == 42
        assert gauge["max"] == 100
        assert len(gauge["zones"]) == 4


class TestKPICards:
    def test_card_count(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        assert len(cards) == 4

    def test_total_units(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        assert cards[0]["value"] == "156"

    def test_total_vacant(self, combined_metrics):
        cards = viz.generate_kpi_cards(combined_metrics)
        assert cards[2]["value"] == "18"  # 2+5+5+6


class TestDataTable:
    def test_row_count(self, combined_metrics):
        table = viz.generate_data_table(combined_metrics)
        assert len(table["rows"]) == 4

    def test_b1_values(self, combined_metrics):
        table = viz.generate_data_table(combined_metrics)
        b1 = [r for r in table["rows"] if r["unit_type"] == "B1"][0]
        assert b1["occupied"] == 19
        assert b1["vacant"] == 5
        assert b1["occ_rate"] == 0.79
        assert b1["asking"] == 1525
        assert b1["comps"] == 1434

    def test_highlights_include_b1(self, combined_metrics):
        table = viz.generate_data_table(combined_metrics)
        assert len(table["highlights"]) > 0
        occ_highlights = [h for h in table["highlights"] if h["col"] == "occ_rate"]
        assert any(h["color"] == "#DC2626" for h in occ_highlights)  # B1 crisis color


class TestRentWaterfall:
    def test_b1_waterfall(self):
        wf = viz.generate_rent_waterfall("B1")
        assert len(wf) == 6
        assert wf[0]["value"] == 1405  # Base
        assert wf[1]["value"] == 125   # Amenity
        assert wf[2]["value"] == 1530  # Predicted
        assert wf[3]["value"] == 1525  # Asking
        assert wf[4]["value"] == 1434  # Comps

    def test_a1_waterfall(self):
        wf = viz.generate_rent_waterfall("A1")
        assert wf[0]["value"] == 1240
        assert wf[2]["value"] == 1329  # predicted = 1240 + 89


class TestLineCharts:
    def test_four_unit_types(self):
        charts = viz.generate_line_charts()
        assert len(charts) == 4
        codes = {c["unit_type"] for c in charts}
        assert codes == {"A1", "A2", "B1", "B2"}

    def test_b1_occupancy_trend(self):
        charts = viz.generate_line_charts()
        b1 = [c for c in charts if c["unit_type"] == "B1"][0]
        occ_values = [s["occupancy"] for s in b1["series"]]
        assert occ_values == [0.88, 0.83, 0.79, 0.79]

    def test_b1_comps_trend(self):
        charts = viz.generate_line_charts()
        b1 = [c for c in charts if c["unit_type"] == "B1"][0]
        comp_values = [s["comps"] for s in b1["series"]]
        assert comp_values == [1475, 1460, 1445, 1434]


class TestStackedBar:
    def test_bar_values(self, metrics_b):
        bars = viz.generate_stacked_bar(metrics_b)
        costs = {b["unit_type"]: b["vacancy_cost"] for b in bars}
        assert costs["B1"] == 7625   # 5 * 1525
        assert costs["B2"] == 9924   # 6 * 1654

    def test_sorted_descending(self, metrics_b):
        bars = viz.generate_stacked_bar(metrics_b)
        costs = [b["vacancy_cost"] for b in bars]
        assert costs == sorted(costs, reverse=True)


class TestDailyBurn:
    def test_daily_burn_values(self, combined_metrics):
        burn = viz.generate_daily_burn_counter(combined_metrics)
        # Total: 91 + 235 + 254 + 331 = 911
        assert burn["daily_amount"] == 911
        assert burn["monthly_amount"] == 911 * 30
        assert burn["annual_amount"] == 911 * 365


class TestBeforeAfter:
    def test_has_three_metrics(self, combined_metrics):
        ba = viz.generate_before_after(combined_metrics, {})
        assert len(ba) == 3
        metric_names = {item["metric"] for item in ba}
        assert "Blended Occupancy" in metric_names
        assert "Total Vacant" in metric_names
        assert "Monthly Vacancy Cost" in metric_names
