"""Portfolio visualization data service — deterministic chart data generators.

NEVER generated by Claude. All data comes from aggregate_cross_property() output.
Each function returns Recharts-compatible data structures.
"""
from app.engine.utils import round_half_up, safe_divide


def generate_portfolio_score_gauge(cross_property_data: dict) -> dict:
    """Portfolio score gauge using portfolio_revenue_efficiency.

    Uses the 5-zone revenue efficiency label system.
    """
    aggregate = cross_property_data.get("aggregate", {})
    score = aggregate.get("portfolio_revenue_efficiency", 0)

    return {
        "score": score,
        "max": 100,
        "zones": [
            {"min": 0, "max": 39, "color": "#DC2626", "label": "Crisis"},
            {"min": 40, "max": 54, "color": "#D97706", "label": "Distressed"},
            {"min": 55, "max": 69, "color": "#F59E0B", "label": "Imbalanced"},
            {"min": 70, "max": 84, "color": "#3B82F6", "label": "Opportunity"},
            {"min": 85, "max": 100, "color": "#059669", "label": "Optimized"},
        ],
    }


def generate_portfolio_kpi_cards(cross_property_data: dict) -> list[dict]:
    """6 portfolio KPI cards for executive summary slide.

    Includes Revenue Gap, Renewal Opportunity, and Revenue Efficiency
    alongside standard occupancy/vacancy cards.
    """
    aggregate = cross_property_data.get("aggregate", {})

    total_units = aggregate.get("total_units", 0)
    total_vacant = aggregate.get("total_vacant", 0)
    blended_occ = aggregate.get("blended_occupancy", 0)
    total_gap = aggregate.get("total_revenue_gap", 0)
    total_renewal = aggregate.get("total_renewal_opportunity", 0)
    rev_efficiency = aggregate.get("portfolio_revenue_efficiency", 0)

    return [
        {
            "label": "Total Units",
            "value": str(total_units),
            "format": "number",
            "color": "#6B7280",
            "trend": "neutral",
        },
        {
            "label": "Blended Occupancy",
            "value": f"{blended_occ:.1%}",
            "format": "percent",
            "color": "#D97706" if blended_occ < 0.92 else "#059669",
            "trend": "down" if blended_occ < 0.94 else "up",
        },
        {
            "label": "Total Vacant",
            "value": str(total_vacant),
            "format": "number",
            "color": "#DC2626" if total_vacant > 10 else "#D97706",
            "trend": "up",
        },
        {
            "label": "Revenue Gap $/mo",
            "value": f"${total_gap:,.0f}",
            "format": "currency",
            "color": "#DC2626" if total_gap > 10000 else "#D97706",
            "trend": "up",
        },
        {
            "label": "Renewal Opportunity $/yr",
            "value": f"${total_renewal:,.0f}",
            "format": "currency",
            "color": "#059669" if total_renewal > 0 else "#6B7280",
            "trend": "up" if total_renewal > 0 else "neutral",
        },
        {
            "label": "Revenue Efficiency %",
            "value": f"{rev_efficiency:.1f}%",
            "format": "percent",
            "color": (
                "#DC2626" if rev_efficiency < 50
                else "#D97706" if rev_efficiency < 75
                else "#059669"
            ),
            "trend": "down" if rev_efficiency < 65 else "up",
        },
    ]


def generate_property_ranking_cards(cross_property_data: dict) -> list[dict]:
    """Property ranking cards ordered by revenue efficiency (worst first).

    Each card shows property name, efficiency score, gap, and unit count.
    """
    ranking = cross_property_data.get("property_ranking", [])

    cards = []
    for entry in ranking:
        eff = entry.get("revenue_efficiency", 0)
        gap = entry.get("revenue_gap", 0)

        if eff >= 85:
            grade_color = "#059669"
            grade_label = "Optimized"
        elif eff >= 70:
            grade_color = "#3B82F6"
            grade_label = "Opportunity"
        elif eff >= 55:
            grade_color = "#F59E0B"
            grade_label = "Imbalanced"
        elif eff >= 40:
            grade_color = "#D97706"
            grade_label = "Distressed"
        else:
            grade_color = "#DC2626"
            grade_label = "Crisis"

        cards.append({
            "property_name": entry.get("property_name", ""),
            "revenue_efficiency": eff,
            "revenue_gap": gap,
            "total_units": entry.get("total_units", 0),
            "total_vacant": entry.get("total_vacant", 0),
            "vacancy_cost": entry.get("vacancy_cost", 0),
            "grade_label": grade_label,
            "grade_color": grade_color,
        })

    return cards


def generate_portfolio_revenue_gap_waterfall(cross_property_data: dict) -> dict:
    """Aggregate revenue gap waterfall across properties.

    Shows which properties contribute the most to the total gap.
    Returns a waterfall-style chart with per-property segments.
    """
    aggregate = cross_property_data.get("aggregate", {})
    properties = cross_property_data.get("properties", {})

    current_revenue = aggregate.get("total_current_revenue", 0)
    optimal_revenue = aggregate.get("total_optimal_revenue", 0)

    # Sort properties by gap descending for waterfall ordering
    sorted_props = sorted(
        properties.items(),
        key=lambda item: item[1].get("revenue_gap", 0),
        reverse=True,
    )

    segments = [
        {
            "label": "Current Portfolio Revenue",
            "value": current_revenue,
            "type": "base",
        },
    ]

    for prop_key, prop_data in sorted_props:
        gap = prop_data.get("revenue_gap", 0)
        if gap > 0:
            segments.append({
                "label": f"+ {prop_data.get('property_name', prop_key)} Gap",
                "value": gap,
                "type": "addition",
                "color": "#DC2626" if gap > 5000 else "#D97706",
            })

    segments.append({
        "label": "= Optimal Portfolio Revenue",
        "value": optimal_revenue,
        "type": "total",
    })

    return {"segments": segments}


def generate_portfolio_revenue_stacked_bar(cross_property_data: dict) -> dict:
    """Stacked bar showing revenue metrics by property.

    Each bar is a property; stacked sections show current revenue,
    revenue gap, and renewal opportunity.
    """
    properties = cross_property_data.get("properties", {})

    bars = []
    for prop_key, prop_data in properties.items():
        # Extract per-property revenue totals from unit type data
        ut_metrics = prop_data.get("unit_type_metrics", {})

        current_rev = sum(
            m.get("optimal_pricing", {}).get("current_revenue_monthly", 0)
            for m in ut_metrics.values()
        )
        gap = prop_data.get("revenue_gap", 0)
        renewal_monthly = prop_data.get("renewal_opportunity", 0) / 12 if prop_data.get("renewal_opportunity", 0) else 0

        bars.append({
            "property": prop_data.get("property_name", prop_key),
            "current_revenue": current_rev,
            "revenue_gap": gap,
            "renewal_opportunity_monthly": round(renewal_monthly, 0),
            "total_potential": current_rev + gap,
        })

    return {"bars": bars}
