"""Visualization data service — deterministic chart data generators.

NEVER generated by Claude. All data comes from metrics engine output.
Each function returns Recharts-compatible data structures.
"""
from app.engine.utils import round_half_up, safe_divide

# The EliseAI Pricing Export ground truth
EXPORT_DATA = {
    "A1": {"bed": 1, "bath": 1, "total": 48, "occupied": 46, "on_notice": 1, "available": 3, "vacant": 2,
            "occ": 0.96, "dom": 24, "dv": 17, "demand": 0.63, "tot_exp": 0.06, "vac_exp": 0.04,
            "exp_30": 0.06, "exp_60": 0.06, "exp_90": 0.06,
            "base": 1240, "amenity": 89, "in_place": 1269, "executed": 1324, "asking": 1365, "predicted": 1329, "comps": 1353},
    "A2": {"bed": 2, "bath": 1, "total": 36, "occupied": 31, "on_notice": 1, "available": 6, "vacant": 5,
            "occ": 0.86, "dom": 22, "dv": 16, "demand": 0.63, "tot_exp": 0.17, "vac_exp": 0.14,
            "exp_30": 0.17, "exp_60": 0.17, "exp_90": 0.17,
            "base": 1275, "amenity": 83, "in_place": 1304, "executed": 1392, "asking": 1411, "predicted": 1358, "comps": 1396},
    "B1": {"bed": 1, "bath": 1, "total": 24, "occupied": 19, "on_notice": 1, "available": 6, "vacant": 5,
            "occ": 0.79, "dom": 25, "dv": 20, "demand": 0.75, "tot_exp": 0.25, "vac_exp": 0.21,
            "exp_30": 0.21, "exp_60": 0.25, "exp_90": 0.25,
            "base": 1405, "amenity": 125, "in_place": 1572, "executed": 1655, "asking": 1525, "predicted": 1530, "comps": 1434},
    "B2": {"bed": 2, "bath": 2, "total": 48, "occupied": 42, "on_notice": 0, "available": 6, "vacant": 6,
            "occ": 0.88, "dom": 30, "dv": 28, "demand": 0.75, "tot_exp": 0.13, "vac_exp": 0.13,
            "exp_30": 0.10, "exp_60": 0.10, "exp_90": 0.10,
            "base": 1465, "amenity": 118, "in_place": 1608, "executed": 1659, "asking": 1654, "predicted": 1583, "comps": 1662},
}

SNAPSHOT_TRENDS = {
    "A1": [
        {"month": "Dec 2025", "occupancy": 0.98, "asking": 1345, "comps": 1340},
        {"month": "Jan 2026", "occupancy": 0.96, "asking": 1355, "comps": 1348},
        {"month": "Feb 2026", "occupancy": 0.96, "asking": 1360, "comps": 1351},
        {"month": "Mar 2026", "occupancy": 0.96, "asking": 1365, "comps": 1353},
    ],
    "A2": [
        {"month": "Dec 2025", "occupancy": 0.92, "asking": 1385, "comps": 1380},
        {"month": "Jan 2026", "occupancy": 0.89, "asking": 1395, "comps": 1388},
        {"month": "Feb 2026", "occupancy": 0.86, "asking": 1405, "comps": 1393},
        {"month": "Mar 2026", "occupancy": 0.86, "asking": 1411, "comps": 1396},
    ],
    "B1": [
        {"month": "Dec 2025", "occupancy": 0.88, "asking": 1600, "comps": 1475},
        {"month": "Jan 2026", "occupancy": 0.83, "asking": 1575, "comps": 1460},
        {"month": "Feb 2026", "occupancy": 0.79, "asking": 1540, "comps": 1445},
        {"month": "Mar 2026", "occupancy": 0.79, "asking": 1525, "comps": 1434},
    ],
    "B2": [
        {"month": "Dec 2025", "occupancy": 0.90, "asking": 1640, "comps": 1650},
        {"month": "Jan 2026", "occupancy": 0.90, "asking": 1650, "comps": 1655},
        {"month": "Feb 2026", "occupancy": 0.88, "asking": 1650, "comps": 1660},
        {"month": "Mar 2026", "occupancy": 0.88, "asking": 1654, "comps": 1662},
    ],
}


def generate_score_gauge(diagnosis: dict, metrics: dict | None = None) -> dict:
    """Slide 2: Portfolio health score gauge with 5-zone system.

    Reads revenue_efficiency from metrics if available; falls back to
    diagnosis portfolio score.
    """
    score = 50
    # Prefer revenue_efficiency score from metrics
    if metrics:
        re_section = metrics.get("revenue_efficiency", {})
        if re_section and "revenue_efficiency_score" in re_section:
            score = re_section["revenue_efficiency_score"]
        elif diagnosis and "portfolio_assessment" in diagnosis:
            score = diagnosis["portfolio_assessment"].get("overall_portfolio_score", 50)
    elif diagnosis and "portfolio_assessment" in diagnosis:
        score = diagnosis["portfolio_assessment"].get("overall_portfolio_score", 50)

    return {
        "score": score,
        "max": 100,
        "zones": [
            {"min": 0, "max": 29, "color": "#DC2626", "label": "Crisis"},
            {"min": 30, "max": 49, "color": "#D97706", "label": "Distressed"},
            {"min": 50, "max": 64, "color": "#F59E0B", "label": "Imbalanced"},
            {"min": 65, "max": 79, "color": "#3B82F6", "label": "Opportunity"},
            {"min": 80, "max": 100, "color": "#059669", "label": "Optimized"},
        ],
    }


def generate_kpi_cards(metrics: dict) -> list[dict]:
    """Slide 2: 6 KPI cards for executive summary."""
    portfolio = metrics.get("portfolio_metrics", {})
    total_vacant = portfolio.get("total_vacant", 0)
    total_units = portfolio.get("total_units", 0)
    blended_occ = portfolio.get("blended_occupancy", 0)

    # Revenue gap data (graceful fallback)
    revenue_gap = metrics.get("revenue_gap", {})
    total_gap_monthly = revenue_gap.get("total_gap_monthly", 0)

    # Renewal opportunity data (graceful fallback)
    renewal_opp = metrics.get("renewal_opportunity", {})
    net_annual_capture = renewal_opp.get("net_annual_capture", 0)

    # Revenue efficiency data (graceful fallback)
    rev_eff = metrics.get("revenue_efficiency", {})
    efficiency_score = rev_eff.get("revenue_efficiency_score", 0)

    return [
        {"label": "Total Units", "value": str(total_units), "format": "number",
         "color": "#6B7280", "trend": "neutral"},
        {"label": "Blended Occupancy", "value": f"{blended_occ:.1%}", "format": "percent",
         "color": "#D97706" if blended_occ < 0.92 else "#059669",
         "trend": "down" if blended_occ < 0.94 else "up"},
        {"label": "Total Vacant", "value": str(total_vacant), "format": "number",
         "color": "#DC2626" if total_vacant > 10 else "#D97706", "trend": "up"},
        {"label": "Revenue Gap $/mo", "value": f"${total_gap_monthly:,.0f}", "format": "currency",
         "color": "#DC2626" if total_gap_monthly > 10000 else "#D97706", "trend": "up"},
        {"label": "Renewal Opportunity $/yr", "value": f"${net_annual_capture:,.0f}", "format": "currency",
         "color": "#059669" if net_annual_capture > 0 else "#6B7280",
         "trend": "up" if net_annual_capture > 0 else "neutral"},
        {"label": "Revenue Efficiency %", "value": f"{efficiency_score}%", "format": "percent",
         "color": "#DC2626" if efficiency_score < 50 else "#D97706" if efficiency_score < 75 else "#059669",
         "trend": "down" if efficiency_score < 65 else "up"},
    ]


def generate_data_table(metrics: dict) -> dict:
    """Slide 3: Full portfolio snapshot table matching EliseAI export.

    Includes optimal_asking, revenue_gap, and elasticity_confidence columns
    when data is available. Colors by gap magnitude.
    """
    columns = [
        {"key": "unit_type", "label": "Unit Type", "format": "text"},
        {"key": "bed_bath", "label": "Bed/Bath", "format": "text"},
        {"key": "total", "label": "Total", "format": "number"},
        {"key": "occupied", "label": "Occupied", "format": "number"},
        {"key": "vacant", "label": "Vacant", "format": "number"},
        {"key": "occ_rate", "label": "Occ %", "format": "percent"},
        {"key": "asking", "label": "Asking", "format": "currency"},
        {"key": "predicted", "label": "Predicted", "format": "currency"},
        {"key": "optimal_asking", "label": "Optimal", "format": "currency"},
        {"key": "comps", "label": "Comps", "format": "currency"},
        {"key": "in_place", "label": "In-Place", "format": "currency"},
        {"key": "revenue_gap", "label": "Rev Gap", "format": "currency"},
        {"key": "elasticity_confidence", "label": "Elast. Conf.", "format": "text"},
        {"key": "dom", "label": "DOM", "format": "number"},
        {"key": "exposure", "label": "Exposure", "format": "percent"},
    ]

    ut_metrics = metrics.get("unit_type_metrics", {})

    rows = []
    highlights = []
    for i, (code, d) in enumerate(EXPORT_DATA.items()):
        # Get optimal pricing data if available
        ut_m = ut_metrics.get(code, {})
        optimal_pricing = ut_m.get("optimal_pricing", {})
        optimal_asking = optimal_pricing.get("optimal_asking", None)

        # Get revenue gap for this unit type
        ut_revenue_gap = ut_m.get("revenue_gap", {})
        unit_gap = ut_revenue_gap.get("total_gap_monthly", 0)

        # Get elasticity confidence
        elasticity = ut_m.get("elasticity", {})
        elast_conf = elasticity.get("confidence", "N/A")

        row = {
            "unit_type": code,
            "bed_bath": f"{d['bed']}/{d['bath']}",
            "total": d["total"],
            "occupied": d["occupied"],
            "vacant": d["vacant"],
            "occ_rate": d["occ"],
            "asking": d["asking"],
            "predicted": d["predicted"],
            "optimal_asking": optimal_asking if optimal_asking is not None else d["asking"],
            "comps": d["comps"],
            "in_place": d["in_place"],
            "revenue_gap": unit_gap,
            "elasticity_confidence": elast_conf,
            "dom": d["dom"],
            "exposure": d["tot_exp"],
        }
        rows.append(row)

        # Highlight critical cells — color by gap magnitude in addition to occupancy
        if d["occ"] < 0.82:
            highlights.append({"row": i, "col": "occ_rate", "color": "#DC2626"})
        elif d["occ"] < 0.88:
            highlights.append({"row": i, "col": "occ_rate", "color": "#D97706"})
        if d["tot_exp"] >= 0.20:
            highlights.append({"row": i, "col": "exposure", "color": "#DC2626"})

        # Color by revenue gap magnitude
        if unit_gap > 5000:
            highlights.append({"row": i, "col": "revenue_gap", "color": "#DC2626"})
        elif unit_gap > 2000:
            highlights.append({"row": i, "col": "revenue_gap", "color": "#D97706"})

    return {"columns": columns, "rows": rows, "highlights": highlights}


def generate_rent_waterfall(code: str, metrics: dict | None = None) -> list[dict]:
    """Slides 4-5: Rent waterfall for a unit type.

    Includes an 'Optimal' bar between Predicted and Asking when
    optimal_asking is available from metrics.
    """
    d = EXPORT_DATA[code]

    bars = [
        {"label": "Base Rent", "value": d["base"], "type": "base", "color": "#6B7280"},
        {"label": f"+ Amenity (${d['amenity']})", "value": d["amenity"], "type": "addition", "color": "#0D9488"},
        {"label": "= Predicted", "value": d["predicted"], "type": "subtotal", "color": "#1F2937"},
    ]

    # Insert Optimal bar if data available
    if metrics:
        ut_m = metrics.get("unit_type_metrics", {}).get(code, {})
        optimal_pricing = ut_m.get("optimal_pricing", {})
        optimal_asking = optimal_pricing.get("optimal_asking")
        if optimal_asking is not None:
            bars.append({"label": "Optimal", "value": optimal_asking, "type": "comparison", "color": "#7C3AED"})

    bars.extend([
        {"label": "Asking", "value": d["asking"], "type": "comparison", "color": "#7C3AED" if not metrics else "#2563EB"},
        {"label": "Comps", "value": d["comps"], "type": "comparison", "color": "#2563EB" if not metrics else "#0D9488"},
        {"label": "In-Place", "value": d["in_place"], "type": "comparison", "color": "#059669"},
    ])
    return bars


def generate_dual_score_card(diagnosis: dict, prop_code: str) -> list[dict]:
    """Slides 4-5: Score cards for unit types in a property."""
    if not diagnosis or "unit_type_assessments" not in diagnosis:
        return []

    codes = {"A": ["A1", "A2"], "B": ["B1", "B2"]}.get(prop_code, [])
    cards = []
    for a in diagnosis["unit_type_assessments"]:
        if a["unit_type"] in codes:
            grade = a.get("grade", "WATCH")
            color = {"HEALTHY": "#059669", "WATCH": "#F59E0B", "ACTION_NEEDED": "#D97706", "CRITICAL": "#DC2626"}.get(grade, "#6B7280")
            cards.append({
                "unit_type": a["unit_type"],
                "score": a.get("health_score", 50),
                "grade": grade,
                "color": color,
                "key_metric": a.get("score_reasoning", "")[:100],
            })
    return cards


def generate_line_charts(metrics: dict | None = None) -> list[dict]:
    """Slide 6: Trend line charts for all 4 unit types.

    Adds optimal price trend data if available from metrics.
    """
    charts = []
    for code, series in SNAPSHOT_TRENDS.items():
        chart_entry: dict = {"unit_type": code, "series": series}

        # Add optimal price trend if metrics available
        if metrics:
            ut_m = metrics.get("unit_type_metrics", {}).get(code, {})
            optimal_pricing = ut_m.get("optimal_pricing", {})
            optimal_asking = optimal_pricing.get("optimal_asking")
            if optimal_asking is not None:
                chart_entry["optimal_price"] = optimal_asking

        charts.append(chart_entry)
    return charts


def generate_revenue_gap_waterfall(metrics: dict) -> dict:
    """Slide 7: Horizontal waterfall showing gap decomposition by lever.

    Takes the revenue_gap section from metrics. Returns segment data
    for a waterfall chart showing how each lever contributes to the gap.
    """
    revenue_gap = metrics.get("revenue_gap", {})

    current_monthly = revenue_gap.get("current_monthly_revenue", 0)
    optimal_monthly = revenue_gap.get("optimal_monthly_revenue", 0)
    vacancy_cost = revenue_gap.get("vacancy_cost", 0)
    new_lease_underpricing = revenue_gap.get("new_lease_underpricing", 0)
    renewal_opportunity = revenue_gap.get("renewal_opportunity", 0)
    concession_drag = revenue_gap.get("concession_drag", 0)

    return {
        "segments": [
            {"label": "Current Revenue", "value": current_monthly, "type": "base"},
            {"label": "+ Fill Vacant", "value": vacancy_cost, "type": "addition", "color": "#DC2626"},
            {"label": "+ Reprice Leases", "value": new_lease_underpricing, "type": "addition", "color": "#D97706"},
            {"label": "+ Capture Renewals", "value": renewal_opportunity, "type": "addition", "color": "#059669"},
            {"label": "- Concession Drag", "value": -concession_drag, "type": "subtraction", "color": "#6B7280"},
            {"label": "= Optimal Revenue", "value": optimal_monthly, "type": "total"},
        ]
    }


def generate_revenue_roadmap(metrics: dict, action_plan: dict) -> dict:
    """Slide 12: Before/after bars with per-lever dollar amounts.

    Returns current vs projected monthly revenue with lever breakdown.
    """
    revenue_gap = metrics.get("revenue_gap", {})
    current_monthly = revenue_gap.get("current_monthly_revenue", 0)
    optimal_monthly = revenue_gap.get("optimal_monthly_revenue", 0)

    vacancy_cost = revenue_gap.get("vacancy_cost", 0)
    new_lease_underpricing = revenue_gap.get("new_lease_underpricing", 0)
    renewal_opportunity = revenue_gap.get("renewal_opportunity", 0)
    concession_drag = revenue_gap.get("concession_drag", 0)

    # Projected = current + all levers (conservative: assume partial capture)
    projected_monthly = current_monthly + vacancy_cost + new_lease_underpricing + renewal_opportunity - concession_drag
    # Cap at optimal if projected exceeds it
    if optimal_monthly > 0:
        projected_monthly = min(projected_monthly, optimal_monthly)

    return {
        "current_monthly": current_monthly,
        "projected_monthly": projected_monthly,
        "levers": [
            {"label": "Fill Vacant Units", "amount": vacancy_cost, "lever": "FILL"},
            {"label": "Reprice New Leases", "amount": new_lease_underpricing, "lever": "REPRICE"},
            {"label": "Capture Renewals", "amount": renewal_opportunity, "lever": "RENEW"},
            {"label": "Remove Concessions", "amount": concession_drag, "lever": "DE_CONCESSION"},
        ]
    }


def generate_dimension_breakdown(metrics: dict) -> dict:
    """Slide 2: Horizontal stacked bar of occ/pricing/momentum scores and weights.

    Reads from revenue_efficiency section if available, otherwise provides
    sensible defaults.
    """
    rev_eff = metrics.get("revenue_efficiency", {})
    dimensions_data = rev_eff.get("dimensions", {})

    occ_health = dimensions_data.get("occupancy_health", {})
    pricing_align = dimensions_data.get("pricing_alignment", {})
    rent_momentum = dimensions_data.get("rent_roll_momentum", {})

    occ_score = occ_health.get("score", 50)
    occ_weight = occ_health.get("weight", 0.40)
    pricing_score = pricing_align.get("score", 50)
    pricing_weight = pricing_align.get("weight", 0.35)
    momentum_score = rent_momentum.get("score", 50)
    momentum_weight = rent_momentum.get("weight", 0.25)

    occupancy_zone = rev_eff.get("occupancy_zone", "BALANCED")
    composite_score = rev_eff.get("revenue_efficiency_score", 50)

    return {
        "dimensions": [
            {"name": "Occupancy Health", "score": occ_score, "weight": occ_weight, "color": "#3B82F6"},
            {"name": "Pricing Alignment", "score": pricing_score, "weight": pricing_weight, "color": "#8B5CF6"},
            {"name": "Rent Roll Momentum", "score": momentum_score, "weight": momentum_weight, "color": "#10B981"},
        ],
        "occupancy_zone": occupancy_zone,
        "composite_score": composite_score,
    }


def generate_daily_burn_counter(metrics: dict) -> dict:
    """Slide 7: Daily burn rate counter."""
    total_daily = sum(
        m["revenue_metrics"]["daily_vacancy_burn"]
        for m in metrics.get("unit_type_metrics", {}).values()
    )
    return {
        "daily_amount": total_daily,
        "monthly_amount": total_daily * 30,
        "annual_amount": total_daily * 365,
    }


def generate_timeline(action_plan: dict) -> list[dict]:
    """Slide 8: Phase timeline."""
    if not action_plan or "phases" not in action_plan:
        return []

    colors = ["#DC2626", "#D97706", "#7C3AED", "#059669"]
    timeline = []
    for phase in action_plan["phases"]:
        actions = phase.get("actions", [])
        exp_count = sum(1 for a in actions if "EXPERIMENT" in a.get("action_type", ""))
        timeline.append({
            "phase": phase["phase_number"],
            "title": phase["name"],
            "days": phase["days"],
            "actions_count": len(actions),
            "experiments_count": exp_count,
            "color": colors[phase["phase_number"] - 1] if phase["phase_number"] <= 4 else "#6B7280",
        })
    return timeline


def generate_action_cards(action_plan: dict) -> list[dict]:
    """Slide 9: Phase 1 action cards."""
    if not action_plan or "phases" not in action_plan:
        return []

    phase1 = action_plan["phases"][0] if action_plan["phases"] else {"actions": []}
    urgency_colors = {
        "REDUCE_ASKING_RENT": "#DC2626",
        "FREEZE_RENEWAL_INCREASES": "#D97706",
        "LAUNCH_PRICE_EXPERIMENT": "#7C3AED",
        "OFFER_MOVE_IN_CONCESSION": "#D97706",
    }

    cards = []
    for a in phase1.get("actions", []):
        action_type = a.get("action_type", "")
        cards.append({
            "title": a.get("description", "")[:80],
            "unit_type": a.get("unit_type", ""),
            "action_type": action_type,
            "target": f"${a['target_value']:,.0f}" if a.get("target_value") else "N/A",
            "urgency": "CRITICAL" if "REDUCE" in action_type else "HIGH",
            "border_color": urgency_colors.get(action_type, "#6B7280"),
        })
    return cards


def generate_experiment_diagram(action_plan: dict) -> list[dict]:
    """Slide 9: Experiment arm diagrams."""
    if not action_plan:
        return []

    experiments = action_plan.get("experiment_summary", [])
    diagrams = []
    arm_colors = ["#6B7280", "#7C3AED", "#0D9488"]

    for exp in experiments:
        arms = []
        for i, arm in enumerate(exp.get("arms", [])):
            arms.append({
                "label": arm.get("label", ""),
                "price": arm.get("price", 0),
                "units": arm.get("units", 0),
                "color": arm_colors[i % len(arm_colors)],
            })
        diagrams.append({
            "unit_type": exp.get("unit_type", ""),
            "arms": arms,
            "window_days": exp.get("observation_days", 14),
        })
    return diagrams


def generate_decision_flowchart(action_plan: dict) -> list[dict]:
    """Slide 10: Decision tree flowcharts."""
    if not action_plan or "decision_points" not in action_plan:
        return []

    flowcharts = []
    for dp in action_plan.get("decision_points", []):
        # Group conditions by unit type mention
        outcomes = []
        for cond in dp.get("conditions", []):
            color = "#059669" if "hold" in cond["then_action"].lower() or "converge" in cond["then_action"].lower() else "#D97706"
            outcomes.append({
                "label": cond["if_condition"],
                "action": cond["then_action"],
                "color": color,
            })
        flowcharts.append({
            "unit_type": "Portfolio",
            "condition": dp.get("description", ""),
            "outcomes": outcomes,
        })
    return flowcharts


def generate_investigation_table(diagnosis: dict) -> list[dict]:
    """Slide 11: Further investigation items."""
    if not diagnosis or "further_investigation" not in diagnosis:
        return []

    return [
        {
            "area": item.get("area", ""),
            "questions": [item.get("reason", "")],
            "data_needed": item.get("data_needed", ""),
            "deadline": "Day 14",
        }
        for item in diagnosis.get("further_investigation", [])
    ]


def generate_before_after(metrics: dict, action_plan: dict) -> list[dict]:
    """Slide 12: Before/after comparison."""
    portfolio = metrics.get("portfolio_metrics", {})
    total_vacant = portfolio.get("total_vacant", 0)
    total_units = portfolio.get("total_units", 0)
    blended_occ = portfolio.get("blended_occupancy", 0)
    total_cost = portfolio.get("total_monthly_vacancy_cost", 0)

    # Projected improvements (conservative estimates)
    projected_vacancy_reduction = max(1, total_vacant // 3)
    projected_occ = round_half_up(safe_divide(total_units - total_vacant + projected_vacancy_reduction, total_units), 2)
    projected_cost = round(total_cost * 0.7)

    return [
        {"metric": "Blended Occupancy", "current": f"{blended_occ:.1%}", "projected": f"{projected_occ:.1%}", "improvement": f"+{(projected_occ - blended_occ):.1%}", "color": "#059669"},
        {"metric": "Total Vacant", "current": str(total_vacant), "projected": str(total_vacant - projected_vacancy_reduction), "improvement": f"-{projected_vacancy_reduction}", "color": "#059669"},
        {"metric": "Monthly Vacancy Cost", "current": f"${total_cost:,.0f}", "projected": f"${projected_cost:,.0f}", "improvement": f"-${total_cost - projected_cost:,.0f}", "color": "#059669"},
    ]
