"""Visualization data service — deterministic chart data generators.

NEVER generated by Claude. All data comes from metrics engine output.
Each function returns Recharts-compatible data structures.
"""
from app.engine.utils import round_half_up, safe_divide

# The EliseAI Pricing Export ground truth
EXPORT_DATA = {
    "A1": {"bed": 1, "bath": 1, "total": 48, "occupied": 46, "on_notice": 1, "available": 3, "vacant": 2,
            "occ": 0.96, "dom": 24, "dv": 17, "demand": 0.63, "tot_exp": 0.06, "vac_exp": 0.04,
            "exp_30": 0.06, "exp_60": 0.06, "exp_90": 0.06,
            "base": 1240, "amenity": 89, "in_place": 1269, "executed": 1324, "asking": 1365, "predicted": 1329, "comps": 1353},
    "A2": {"bed": 2, "bath": 1, "total": 36, "occupied": 31, "on_notice": 1, "available": 6, "vacant": 5,
            "occ": 0.86, "dom": 22, "dv": 16, "demand": 0.63, "tot_exp": 0.17, "vac_exp": 0.14,
            "exp_30": 0.17, "exp_60": 0.17, "exp_90": 0.17,
            "base": 1275, "amenity": 83, "in_place": 1304, "executed": 1392, "asking": 1411, "predicted": 1358, "comps": 1396},
    "B1": {"bed": 1, "bath": 1, "total": 24, "occupied": 19, "on_notice": 1, "available": 6, "vacant": 5,
            "occ": 0.79, "dom": 25, "dv": 20, "demand": 0.75, "tot_exp": 0.25, "vac_exp": 0.21,
            "exp_30": 0.21, "exp_60": 0.25, "exp_90": 0.25,
            "base": 1405, "amenity": 125, "in_place": 1572, "executed": 1655, "asking": 1525, "predicted": 1530, "comps": 1434},
    "B2": {"bed": 2, "bath": 2, "total": 48, "occupied": 42, "on_notice": 0, "available": 6, "vacant": 6,
            "occ": 0.88, "dom": 30, "dv": 28, "demand": 0.75, "tot_exp": 0.13, "vac_exp": 0.13,
            "exp_30": 0.10, "exp_60": 0.10, "exp_90": 0.10,
            "base": 1465, "amenity": 118, "in_place": 1608, "executed": 1659, "asking": 1654, "predicted": 1583, "comps": 1662},
}

SNAPSHOT_TRENDS = {
    "A1": [
        {"month": "Dec 2025", "occupancy": 0.98, "asking": 1345, "comps": 1340},
        {"month": "Jan 2026", "occupancy": 0.96, "asking": 1355, "comps": 1348},
        {"month": "Feb 2026", "occupancy": 0.96, "asking": 1360, "comps": 1351},
        {"month": "Mar 2026", "occupancy": 0.96, "asking": 1365, "comps": 1353},
    ],
    "A2": [
        {"month": "Dec 2025", "occupancy": 0.92, "asking": 1385, "comps": 1380},
        {"month": "Jan 2026", "occupancy": 0.89, "asking": 1395, "comps": 1388},
        {"month": "Feb 2026", "occupancy": 0.86, "asking": 1405, "comps": 1393},
        {"month": "Mar 2026", "occupancy": 0.86, "asking": 1411, "comps": 1396},
    ],
    "B1": [
        {"month": "Dec 2025", "occupancy": 0.88, "asking": 1600, "comps": 1475},
        {"month": "Jan 2026", "occupancy": 0.83, "asking": 1575, "comps": 1460},
        {"month": "Feb 2026", "occupancy": 0.79, "asking": 1540, "comps": 1445},
        {"month": "Mar 2026", "occupancy": 0.79, "asking": 1525, "comps": 1434},
    ],
    "B2": [
        {"month": "Dec 2025", "occupancy": 0.90, "asking": 1640, "comps": 1650},
        {"month": "Jan 2026", "occupancy": 0.90, "asking": 1650, "comps": 1655},
        {"month": "Feb 2026", "occupancy": 0.88, "asking": 1650, "comps": 1660},
        {"month": "Mar 2026", "occupancy": 0.88, "asking": 1654, "comps": 1662},
    ],
}


def generate_score_gauge(diagnosis: dict) -> dict:
    """Slide 2: Portfolio health score gauge."""
    score = 50
    if diagnosis and "portfolio_assessment" in diagnosis:
        score = diagnosis["portfolio_assessment"].get("overall_portfolio_score", 50)
    return {
        "score": score,
        "max": 100,
        "zones": [
            {"min": 0, "max": 39, "color": "#DC2626", "label": "Critical"},
            {"min": 40, "max": 64, "color": "#D97706", "label": "Action Needed"},
            {"min": 65, "max": 79, "color": "#F59E0B", "label": "Watch"},
            {"min": 80, "max": 100, "color": "#059669", "label": "Healthy"},
        ],
    }


def generate_kpi_cards(metrics: dict) -> list[dict]:
    """Slide 2: 4 KPI cards for executive summary."""
    portfolio = metrics.get("portfolio_metrics", {})
    total_vacant = portfolio.get("total_vacant", 0)
    total_units = portfolio.get("total_units", 0)
    blended_occ = portfolio.get("blended_occupancy", 0)
    total_cost = portfolio.get("total_monthly_vacancy_cost", 0)

    return [
        {"label": "Total Units", "value": str(total_units), "format": "number", "color": "#6B7280", "trend": "neutral"},
        {"label": "Blended Occupancy", "value": f"{blended_occ:.1%}", "format": "percent", "color": "#D97706" if blended_occ < 0.92 else "#059669", "trend": "down" if blended_occ < 0.94 else "up"},
        {"label": "Total Vacant", "value": str(total_vacant), "format": "number", "color": "#DC2626" if total_vacant > 10 else "#D97706", "trend": "up"},
        {"label": "Monthly Vacancy Cost", "value": f"${total_cost:,.0f}", "format": "currency", "color": "#DC2626", "trend": "up"},
    ]


def generate_data_table(metrics: dict) -> dict:
    """Slide 3: Full portfolio snapshot table matching EliseAI export."""
    columns = [
        {"key": "unit_type", "label": "Unit Type", "format": "text"},
        {"key": "bed_bath", "label": "Bed/Bath", "format": "text"},
        {"key": "total", "label": "Total", "format": "number"},
        {"key": "occupied", "label": "Occupied", "format": "number"},
        {"key": "vacant", "label": "Vacant", "format": "number"},
        {"key": "occ_rate", "label": "Occ %", "format": "percent"},
        {"key": "asking", "label": "Asking", "format": "currency"},
        {"key": "predicted", "label": "Predicted", "format": "currency"},
        {"key": "comps", "label": "Comps", "format": "currency"},
        {"key": "in_place", "label": "In-Place", "format": "currency"},
        {"key": "dom", "label": "DOM", "format": "number"},
        {"key": "exposure", "label": "Exposure", "format": "percent"},
    ]

    rows = []
    highlights = []
    for i, (code, d) in enumerate(EXPORT_DATA.items()):
        row = {
            "unit_type": code,
            "bed_bath": f"{d['bed']}/{d['bath']}",
            "total": d["total"],
            "occupied": d["occupied"],
            "vacant": d["vacant"],
            "occ_rate": d["occ"],
            "asking": d["asking"],
            "predicted": d["predicted"],
            "comps": d["comps"],
            "in_place": d["in_place"],
            "dom": d["dom"],
            "exposure": d["tot_exp"],
        }
        rows.append(row)

        # Highlight critical cells
        if d["occ"] < 0.82:
            highlights.append({"row": i, "col": "occ_rate", "color": "#DC2626"})
        elif d["occ"] < 0.88:
            highlights.append({"row": i, "col": "occ_rate", "color": "#D97706"})
        if d["tot_exp"] >= 0.20:
            highlights.append({"row": i, "col": "exposure", "color": "#DC2626"})

    return {"columns": columns, "rows": rows, "highlights": highlights}


def generate_rent_waterfall(code: str) -> list[dict]:
    """Slides 4-5: Rent waterfall for a unit type."""
    d = EXPORT_DATA[code]
    return [
        {"label": "Base Rent", "value": d["base"], "type": "base", "color": "#6B7280"},
        {"label": f"+ Amenity (${d['amenity']})", "value": d["amenity"], "type": "addition", "color": "#0D9488"},
        {"label": "= Predicted", "value": d["predicted"], "type": "subtotal", "color": "#1F2937"},
        {"label": "Asking", "value": d["asking"], "type": "comparison", "color": "#7C3AED"},
        {"label": "Comps", "value": d["comps"], "type": "comparison", "color": "#2563EB"},
        {"label": "In-Place", "value": d["in_place"], "type": "comparison", "color": "#059669"},
    ]


def generate_dual_score_card(diagnosis: dict, prop_code: str) -> list[dict]:
    """Slides 4-5: Score cards for unit types in a property."""
    if not diagnosis or "unit_type_assessments" not in diagnosis:
        return []

    codes = {"A": ["A1", "A2"], "B": ["B1", "B2"]}.get(prop_code, [])
    cards = []
    for a in diagnosis["unit_type_assessments"]:
        if a["unit_type"] in codes:
            grade = a.get("grade", "WATCH")
            color = {"HEALTHY": "#059669", "WATCH": "#F59E0B", "ACTION_NEEDED": "#D97706", "CRITICAL": "#DC2626"}.get(grade, "#6B7280")
            cards.append({
                "unit_type": a["unit_type"],
                "score": a.get("health_score", 50),
                "grade": grade,
                "color": color,
                "key_metric": a.get("score_reasoning", "")[:100],
            })
    return cards


def generate_line_charts() -> list[dict]:
    """Slide 6: Trend line charts for all 4 unit types."""
    return [
        {"unit_type": code, "series": series}
        for code, series in SNAPSHOT_TRENDS.items()
    ]


def generate_stacked_bar(metrics: dict) -> list[dict]:
    """Slide 7: Stacked bar chart of vacancy cost by unit type."""
    bars = []
    for code, m in metrics.get("unit_type_metrics", {}).items():
        cost = m["revenue_metrics"]["monthly_vacancy_cost"]
        color = "#DC2626" if cost > 8000 else "#D97706" if cost > 5000 else "#F59E0B"
        bars.append({"unit_type": code, "vacancy_cost": cost, "color": color})
    return sorted(bars, key=lambda b: b["vacancy_cost"], reverse=True)


def generate_daily_burn_counter(metrics: dict) -> dict:
    """Slide 7: Daily burn rate counter."""
    total_daily = sum(
        m["revenue_metrics"]["daily_vacancy_burn"]
        for m in metrics.get("unit_type_metrics", {}).values()
    )
    return {
        "daily_amount": total_daily,
        "monthly_amount": total_daily * 30,
        "annual_amount": total_daily * 365,
    }


def generate_timeline(action_plan: dict) -> list[dict]:
    """Slide 8: Phase timeline."""
    if not action_plan or "phases" not in action_plan:
        return []

    colors = ["#DC2626", "#D97706", "#7C3AED", "#059669"]
    timeline = []
    for phase in action_plan["phases"]:
        actions = phase.get("actions", [])
        exp_count = sum(1 for a in actions if "EXPERIMENT" in a.get("action_type", ""))
        timeline.append({
            "phase": phase["phase_number"],
            "title": phase["name"],
            "days": phase["days"],
            "actions_count": len(actions),
            "experiments_count": exp_count,
            "color": colors[phase["phase_number"] - 1] if phase["phase_number"] <= 4 else "#6B7280",
        })
    return timeline


def generate_action_cards(action_plan: dict) -> list[dict]:
    """Slide 9: Phase 1 action cards."""
    if not action_plan or "phases" not in action_plan:
        return []

    phase1 = action_plan["phases"][0] if action_plan["phases"] else {"actions": []}
    urgency_colors = {
        "REDUCE_ASKING_RENT": "#DC2626",
        "FREEZE_RENEWAL_INCREASES": "#D97706",
        "LAUNCH_PRICE_EXPERIMENT": "#7C3AED",
        "OFFER_MOVE_IN_CONCESSION": "#D97706",
    }

    cards = []
    for a in phase1.get("actions", []):
        action_type = a.get("action_type", "")
        cards.append({
            "title": a.get("description", "")[:80],
            "unit_type": a.get("unit_type", ""),
            "action_type": action_type,
            "target": f"${a['target_value']:,.0f}" if a.get("target_value") else "N/A",
            "urgency": "CRITICAL" if "REDUCE" in action_type else "HIGH",
            "border_color": urgency_colors.get(action_type, "#6B7280"),
        })
    return cards


def generate_experiment_diagram(action_plan: dict) -> list[dict]:
    """Slide 9: Experiment arm diagrams."""
    if not action_plan:
        return []

    experiments = action_plan.get("experiment_summary", [])
    diagrams = []
    arm_colors = ["#6B7280", "#7C3AED", "#0D9488"]

    for exp in experiments:
        arms = []
        for i, arm in enumerate(exp.get("arms", [])):
            arms.append({
                "label": arm.get("label", ""),
                "price": arm.get("price", 0),
                "units": arm.get("units", 0),
                "color": arm_colors[i % len(arm_colors)],
            })
        diagrams.append({
            "unit_type": exp.get("unit_type", ""),
            "arms": arms,
            "window_days": exp.get("observation_days", 14),
        })
    return diagrams


def generate_decision_flowchart(action_plan: dict) -> list[dict]:
    """Slide 10: Decision tree flowcharts."""
    if not action_plan or "decision_points" not in action_plan:
        return []

    flowcharts = []
    for dp in action_plan.get("decision_points", []):
        # Group conditions by unit type mention
        outcomes = []
        for cond in dp.get("conditions", []):
            color = "#059669" if "hold" in cond["then_action"].lower() or "converge" in cond["then_action"].lower() else "#D97706"
            outcomes.append({
                "label": cond["if_condition"],
                "action": cond["then_action"],
                "color": color,
            })
        flowcharts.append({
            "unit_type": "Portfolio",
            "condition": dp.get("description", ""),
            "outcomes": outcomes,
        })
    return flowcharts


def generate_investigation_table(diagnosis: dict) -> list[dict]:
    """Slide 11: Further investigation items."""
    if not diagnosis or "further_investigation" not in diagnosis:
        return []

    return [
        {
            "area": item.get("area", ""),
            "questions": [item.get("reason", "")],
            "data_needed": item.get("data_needed", ""),
            "deadline": "Day 14",
        }
        for item in diagnosis.get("further_investigation", [])
    ]


def generate_before_after(metrics: dict, action_plan: dict) -> list[dict]:
    """Slide 12: Before/after comparison."""
    portfolio = metrics.get("portfolio_metrics", {})
    total_vacant = portfolio.get("total_vacant", 0)
    total_units = portfolio.get("total_units", 0)
    blended_occ = portfolio.get("blended_occupancy", 0)
    total_cost = portfolio.get("total_monthly_vacancy_cost", 0)

    # Projected improvements (conservative estimates)
    projected_vacancy_reduction = max(1, total_vacant // 3)
    projected_occ = round_half_up(safe_divide(total_units - total_vacant + projected_vacancy_reduction, total_units), 2)
    projected_cost = round(total_cost * 0.7)

    return [
        {"metric": "Blended Occupancy", "current": f"{blended_occ:.1%}", "projected": f"{projected_occ:.1%}", "improvement": f"+{(projected_occ - blended_occ):.1%}", "color": "#059669"},
        {"metric": "Total Vacant", "current": str(total_vacant), "projected": str(total_vacant - projected_vacancy_reduction), "improvement": f"-{projected_vacancy_reduction}", "color": "#059669"},
        {"metric": "Monthly Vacancy Cost", "current": f"${total_cost:,.0f}", "projected": f"${projected_cost:,.0f}", "improvement": f"-${total_cost - projected_cost:,.0f}", "color": "#059669"},
    ]
