"""initial_schema_14_tables

Revision ID: 77e354e140ab
Revises: 
Create Date: 2026-03-17 15:29:18.580948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e354e140ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('submarket', sa.String(length=100), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_class', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_property_org_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_org_created', 'audit_log', ['organization_id', 'created_at'], unique=False)
    op.create_table('client_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('investment_thesis', sa.String(length=50), nullable=True),
    sa.Column('risk_profile', sa.String(length=50), nullable=True),
    sa.Column('hold_period_years', sa.Integer(), nullable=True),
    sa.Column('business_plan_summary', sa.String(length=2000), nullable=True),
    sa.Column('occupancy_thresholds', sa.JSON(), nullable=True),
    sa.Column('exposure_thresholds', sa.JSON(), nullable=True),
    sa.Column('pricing_tolerance', sa.JSON(), nullable=True),
    sa.Column('concession_policy', sa.JSON(), nullable=True),
    sa.Column('renewal_policy', sa.JSON(), nullable=True),
    sa.Column('lease_term_policy', sa.JSON(), nullable=True),
    sa.Column('experiment_policy', sa.JSON(), nullable=True),
    sa.Column('amenity_benchmarks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comp_properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('submarket', sa.String(length=100), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_class', sa.String(length=10), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('bed', sa.Integer(), nullable=False),
    sa.Column('bath', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('base_rent', sa.Float(), nullable=False),
    sa.Column('sqft_min', sa.Integer(), nullable=True),
    sa.Column('sqft_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'code', name='uq_unittype_prop_code')
    )
    op.create_table('comp_unit_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comp_property_id', sa.Uuid(), nullable=False),
    sa.Column('subject_unit_type_id', sa.Uuid(), nullable=False),
    sa.Column('bed', sa.Integer(), nullable=False),
    sa.Column('bath', sa.Integer(), nullable=False),
    sa.Column('sqft_range', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['comp_property_id'], ['comp_properties.id'], ),
    sa.ForeignKeyConstraint(['subject_unit_type_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('flags_json', sa.JSON(), nullable=True),
    sa.Column('diagnosis_json', sa.JSON(), nullable=True),
    sa.Column('action_plan_json', sa.JSON(), nullable=True),
    sa.Column('narrative_json', sa.JSON(), nullable=True),
    sa.Column('slide_deck_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('metrics_compute_ms', sa.Integer(), nullable=True),
    sa.Column('diagnosis_api_ms', sa.Integer(), nullable=True),
    sa.Column('action_plan_api_ms', sa.Integer(), nullable=True),
    sa.Column('narrative_api_ms', sa.Integer(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['client_configs.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_type_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('vacant', sa.Integer(), nullable=False),
    sa.Column('on_notice', sa.Integer(), nullable=False),
    sa.Column('occupancy_rate', sa.Float(), nullable=False),
    sa.Column('avg_in_place_rent', sa.Float(), nullable=True),
    sa.Column('avg_asking_rent', sa.Float(), nullable=True),
    sa.Column('avg_executed_rent', sa.Float(), nullable=True),
    sa.Column('avg_days_on_market', sa.Integer(), nullable=True),
    sa.Column('exposure_pct', sa.Float(), nullable=True),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.Column('comps_avg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_type_id', 'snapshot_date', name='uq_snapshot_type_date')
    )
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_type_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('sqft', sa.Integer(), nullable=False),
    sa.Column('premium_view', sa.Boolean(), nullable=False),
    sa.Column('high_floor', sa.Boolean(), nullable=False),
    sa.Column('corner_unit', sa.Boolean(), nullable=False),
    sa.Column('in_unit_wd', sa.Boolean(), nullable=False),
    sa.Column('renovated', sa.Boolean(), nullable=False),
    sa.Column('patio_balcony', sa.Boolean(), nullable=False),
    sa.Column('ev_charging', sa.Boolean(), nullable=False),
    sa.Column('garage_parking', sa.Boolean(), nullable=False),
    sa.Column('amenity_premium', sa.Float(), nullable=False),
    sa.Column('predicted_rent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_rent', sa.Float(), nullable=True),
    sa.Column('lease_start', sa.Date(), nullable=True),
    sa.Column('lease_end', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('asking_rent', sa.Float(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('days_vacant', sa.Integer(), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('last_executed_rent', sa.Float(), nullable=True),
    sa.Column('last_executed_date', sa.Date(), nullable=True),
    sa.Column('concession_active', sa.Boolean(), nullable=False),
    sa.Column('concession_type', sa.String(length=50), nullable=True),
    sa.Column('concession_value_monthly', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'unit_number', name='uq_unit_prop_number')
    )
    op.create_table('comp_rents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comp_unit_type_id', sa.Uuid(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('asking_rent', sa.Float(), nullable=False),
    sa.Column('concession_advertised', sa.String(length=255), nullable=True),
    sa.Column('net_effective_rent', sa.Float(), nullable=True),
    sa.Column('units_advertised', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comp_unit_type_id'], ['comp_unit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comp_rents_type_date', 'comp_rents', ['comp_unit_type_id', 'observation_date'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnostic_run_id', sa.Uuid(), nullable=False),
    sa.Column('unit_type_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('experiment_design', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('outcome_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnostic_runs.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('arm_label', sa.String(length=50), nullable=False),
    sa.Column('assigned_price', sa.Float(), nullable=False),
    sa.Column('assigned_concession', sa.String(length=255), nullable=True),
    sa.Column('leased', sa.Boolean(), nullable=False),
    sa.Column('lease_date', sa.DateTime(), nullable=True),
    sa.Column('days_to_lease', sa.Integer(), nullable=True),
    sa.Column('application_received', sa.Boolean(), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('tours_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'unit_id', name='uq_experiment_unit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_assignments')
    op.drop_table('experiments')
    op.drop_index('ix_comp_rents_type_date', table_name='comp_rents')
    op.drop_table('comp_rents')
    op.drop_table('units')
    op.drop_table('historical_snapshots')
    op.drop_table('diagnostic_runs')
    op.drop_table('comp_unit_types')
    op.drop_table('unit_types')
    op.drop_table('comp_properties')
    op.drop_table('client_configs')
    op.drop_index('ix_audit_org_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('properties')
    op.drop_table('organizations')
    # ### end Alembic commands ###
